ML LAB 2


1. Consider the given list as [2, 7, 4, 1, 3, 6]. Write a program to count pairs of elements with
sum equal to 10.

In [1]:
list1=[2, 7, 4, 1, 3, 6]
count=0
for i in range(len(list1)):
  for j in range(i+1,len(list1)):
    if list1[i]+list1[j]==10:
      count=count+1
      print(  list1[i],list1[j])
print("count=",count)


7 3
4 6
count= 2


In [2]:
# modularised code
def count_pairs_with_sum(lst, target_sum):

    count = 0
    pairs = []
    for i in range(len(lst)):
        for j in range(i + 1, len(lst)):
            if lst[i] + lst[j] == target_sum:
                count += 1
                pairs.append((lst[i], lst[j]))
    return count, pairs

# Main program
if __name__ == "__main__":
    list1 = [2, 7, 4, 1, 3, 6]
    target_sum = 10
    count, pairs = count_pairs_with_sum(list1, target_sum)

    # Display the pairs
    for pair in pairs:
        print(pair)

    # Display the count of pairs
    print(f"count = {count}")


(7, 3)
(4, 6)
count = 2


2. Write a program that takes a list of real numbers as input and returns the range (difference
between minimum and maximum) of the list. Check for list being less than 3 elements in
which case return an error message (Ex: “Range determination not possible”). Given a list
[5,3,8,1,0,4], the range is 8 (8-0).

In [3]:
list=[5,3,8,1,0,4]
if len(list)<3:
  print("range determination not possible")
else:
  print("range=",max(list)-min(list))

range= 8


In [ ]:

def calculate_range(lst):

    if len(lst) < 3:
        return "Range determination not possible"
    else:
        return max(lst) - min(lst)

# Main program
if __name__ == "__main__":
    list1 = [5, 3, 8, 1, 0, 4]
    range_result = calculate_range(list1)

    if isinstance(range_result, str):
        print(range_result)
    else:
        print(f"Range = {range_result}")


3. Write a program that accepts a square matrix A and a positive integer m as arguments and
returns A^m.

In [9]:
import numpy as np

# Function to calculate A^m
def matrix_power(A, m):
    return np.linalg.matrix_power(A, m)

# Main program
if __name__ == "__main__":

    n = int(input("Enter the size of the square matrix (n x n): "))


    matrix_elements = []


    for i in range(n):
        for j in range(n):
            element = int(input(f"Enter element ({i+1}, {j+1}): "))
            matrix_elements.append(element)


    A = np.array(matrix_elements).reshape(n, n)


    m = int(input("Enter a positive integer m: "))


    result_matrix = matrix_power(A, m)


    print(f"Matrix A raised to the power of {m} is:")
    print(result_matrix)


Enter the size of the square matrix (n x n): 3
Enter element (1, 1): 1
Enter element (1, 2): 2
Enter element (1, 3): 3
Enter element (2, 1): 4
Enter element (2, 2): 5
Enter element (2, 3): 6
Enter element (3, 1): 7
Enter element (3, 2): 8
Enter element (3, 3): 9
Enter a positive integer m: 2
Matrix A raised to the power of 2 is:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Write a program to count the highest occurring character & its occurrence count in an input
string. Consider only alphabets. Ex:  for “hippopotamus” as input string, the maximally
occurring character is ‘p’ & occurrence count is 3.

In [10]:

def highest_occurrence_char(input_string):
    # Creating a dictionary to store the frequency of each character
    frequency = {}

    # Convert the string to lowercase and filter to only consider alphabets
    for char in input_string:
        if char.isalpha():
            char = char.lower()  # Consider characters case-insensitively
            # Count occurrences of each character
            if char in frequency:
                frequency[char] += 1
            else:
                frequency[char] = 1


    max_char = ''
    max_count = 0
    for char, count in frequency.items():
        if count > max_count:
            max_char = char
            max_count = count

    return max_char, max_count


if __name__ == "__main__":

    input_string = input("Enter a string: ")


    char, count = highest_occurrence_char(input_string)


    print(f"The maximally occurring character is '{char}' and its occurrence count is {count}.")


Enter a string: hippopotomus
The maximally occurring character is 'p' and its occurrence count is 3.
